print("Row, Row, Row Your Boat Mad Lib")
print("")
verb = input("Give me a verb: ")
noun1 = input("Give me a noun: ")
noun2 = input("Give me a second noun:")
emotion = input("Give me an emotion: ")
noun3 = input("Give me your third noun: ")
print("")
print(verb, ",", verb, ",", verb, " your ", noun1)
print("Gently down the ", noun2)
print(emotion, ",", emotion, ",", emotion, ",", emotion)
print("Life is but a ", noun3)


print("Johny Johny, Yes Papa Mab Lib")
print("")
name = input("Name: ")
relative = input("Relative relation: ")
food = input("Food?: ")
verb = input("Verb?: ")
part1 = input("Body part?: ")
o = input("Oxymoron: ")

print("")
print(name, ",", name)
print("Yes ", relative)
print("Eating ", food, "?")
print("No", relative)
print(verb, "lies?")
print("No", relative)
print("Open your ", part1)
print(o, o, o)

